lms/urls.py
from django.urls import path
from django.conf.urls import url
from lms import views

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('borrow/', views.borrow, name='borrow'),
    path('record/', views.RecordListView.as_view(), name='record'),
    path('check_in/', views.check_in, name='check_in'),
    path('maintenance/', views.maintenance, name='maintenance'),
    path('search_result_details/', views.search_result_details, name='search_result_details'),
    path('bookinstance_mgt/', views.bookinstance_mgt, name='bookinstance_mgt'),
    path('bookinstance_edit/', views.bookinstance_edit, name='bookinstance_edit'),
    path('book_mgt/', views.BookMgtListView.as_view(), name='book_mgt'),
    path('book_new/', views.book_new, name='book_new'),
    path('book_edit/', views.book_edit, name='book_edit'),
    path('reserve_cancel/', views.reserve_cancel, name='reserve_cancel'),
    path('extend/', views.extend, name='extend'),
    path('picking_list/<str:date>/', views.picking_list, name='picking_list'),
]

mysite/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('lms/', include('lms.urls')),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
]

lms/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User
import re, datetime
from django.core.validators import RegexValidator


class Book(models.Model):
    patten = re.compile(r'[A-Z]\d{2,9}')
    BookID = models.CharField(max_length=64, primary_key=True,
                              validators=[RegexValidator(regex=patten)],
                              help_text='The format is one character and 2 to 9 digits')
    Title = models.TextField()
    Language = models.TextField()
    Author = models.TextField()
    Publisher = models.TextField()
    PublishDate = models.DateField()
    ISBN = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return f'{self.BookID} ({self.Title})'

    def Waiting(self):
        q1 = Q(BookID=self.BookID)
        q2 = Q(ReleaseDate__isnull=True)
        return Reserve.objects.filter(q1 & q2).count()

    def ReserveUser(self):
        q1 = Q(BookID=self.BookID)
        q2 = Q(ReleaseDate__isnull=True)
        if Reserve.objects.filter(q1 & q2).count() > 0:
            y = Reserve.objects.filter(q1 & q2).values_list()[:1].get()[3]
            return User.objects.filter(id = y).values_list("username", flat=True)[0]
        else:
            return ""

class BookInstance(models.Model):
    BookInstanceID = models.CharField(max_length=64, unique=True, primary_key=True)
    BookID = models.ForeignKey(Book, db_column='BookID', on_delete=models.PROTECT)
    BOOK_INSTANCE_STATUS = (
        ('Maintenance', 'Maintenance'),
        ('On Loan', 'On Loan'),
        ('Available', 'Available'),
        ('Suspended', 'Suspended'),
    )
    Status = models.CharField(max_length=15, choices=BOOK_INSTANCE_STATUS, default='a')

    def __str__(self):
        return f'{self.BookInstanceID} ({self.BookID.Title})'

    def DueDate(self):
        q1 = Q(BookInstanceID = self.BookInstanceID)
        q2 = Q(ReturnDate__isnull=True)
        y = BorrowRecord.objects.filter(q1 & q2).values_list('DueDate', flat=True)
        if self.Status == "On Loan":
            return y[0]
        else:
            return ""

    def Username(self):
        q1 = Q(BookInstanceID = self.BookInstanceID)
        q2 = Q(ReturnDate__isnull=True)
        x = BorrowRecord.objects.filter(q1 & q2).values_list('UserID__username', flat=True)
        if self.Status == "On Loan":
            return x[0]
        else:
            return ""

class BorrowRecord(models.Model):
    BorrowID = models.AutoField(primary_key=True)
    BookInstanceID = models.ForeignKey(BookInstance, db_column='BookInstanceID', on_delete=models.PROTECT)
    UserID = models.ForeignKey(User, db_column='UserID', on_delete=models.PROTECT)
    BorrowDate = models.DateField()
    DueDate = models.DateField()
    ReturnDate = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.BorrowID} ({self.BookInstanceID}-{self.UserID})'

    def IsOverdue(self):
        now = datetime.datetime.now().date()
        if self.ReturnDate is None:
            if self.DueDate < now:
                return True
            else:
                return False
        else:
            return False

class Reserve(models.Model):
    ReserveID = models.AutoField(primary_key=True)
    BookID = models.ForeignKey(Book, db_column='BookID', on_delete=models.PROTECT)
    BookInstanceID = models.ForeignKey(BookInstance, db_column='BookInstanceID', on_delete=models.PROTECT, blank=True,
                                       null=True)
    UserID = models.ForeignKey(User, db_column='UserID', on_delete=models.PROTECT)
    ReserveDate = models.DateField()
    ReleaseDate = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.ReserveID} ({self.BookID}-{self.UserID})'

    def Waiting(self):
        q1 = Q(BookID=self.BookID)
        q2 = Q(ReleaseDate__isnull=True)
        q3 = Q(UserID=self.UserID)
        y = Reserve.objects.filter(q1 & q2 & q3).values_list()[:1].get()[0]
        q4 = Q(ReserveID__lt=y)
        return Reserve.objects.filter(q1 & q2 & q4).count() + 1

# Create your models here.

lms/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.forms import ModelForm
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from lms.models import Book, BookInstance, BorrowRecord, Reserve
from django.contrib import messages
from lms.forms import BookModelForm, BookInstanceModelForm
from django.db import transaction
from django.contrib.auth.models import User
import datetime
from django.db.models import Count
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView

class IndexListView(ListView):

    template_name = 'lms/index.html'
    paginate_by = 5

    def get_queryset(self):
        if self.request.GET.get('search'):
            search_text = self.request.GET.get('search')
            q1 = Q(BookID__icontains=search_text)
            q2 = Q(Author__icontains=search_text)
            q3 = Q(Title__icontains=search_text)
            q4 = Q(Publisher__icontains=search_text)
            book_list = Book.objects.filter(q1 | q2 | q3 | q4)
            return book_list
        else:
            now = datetime.datetime.now()
            delta = datetime.timedelta(days=30)
            past30 = now - delta
            q1 = Q(BorrowDate__gt=past30)
            rating = BorrowRecord.objects.filter(q1).values('BookInstanceID__BookID') \
                         .annotate(Count('BookInstanceID__BookID')) \
                         .order_by('-BookInstanceID__BookID__count')[:10]
            top10 = rating.values_list('BookInstanceID__BookID', flat=True)

            book_list = []
            for i in range(10):
                book_list += Book.objects.filter(BookID=top10[i])

            return book_list

    def get_context_data(self, **kwargs):
        context = super(IndexListView, self).get_context_data(**kwargs)
        books = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(books, self.paginate_by)
        try:
            books = paginator.page(page)
        except PageNotAnInteger:
            books = paginator.page(1)
        except EmptyPage:
            books = paginator.page(paginator.num_pages)

        if self.request.GET.get('search'):
            title = 'Search result:'
        else:
            title = 'Top 10 books in 30 days:'

        context['book_list'] = books
        context['title'] = title
        return context

def search_result_details(request):
    book_selected = request.POST['BookID']
    book_list = Book.objects.get(BookID=book_selected)
    bookinstance_list = BookInstance.objects.filter(BookID=book_selected)
    context = {
        'book_list': book_list,
        'bookinstance_list': bookinstance_list,
    }
    return render(request, 'lms/search_result_details.html', context)


def borrow(request):
    book_limit = 10
    borrow_day = 30
    if request.method == 'POST':
        book_selected = request.POST['BookID']
        now = datetime.datetime.now()
        delta = datetime.timedelta(days=borrow_day)
        q1 = Q(BookID=book_selected)
        q2 = Q(Status='Available')
        q3 = Q(UserID=request.user)
        q4 = Q(ReturnDate__isnull=True)
        q5 = Q(ReleaseDate__isnull=True)
        q6 = Q(DueDate__lt=now)
        current_borrow = BorrowRecord.objects.filter(q3 & q4).count()
        current_reserve = Reserve.objects.filter(q3 & q5).count()
        if BorrowRecord.objects.filter(q3 & q4 & q6).count() > 0:
            context = {
                'msg': 'Failed! You have overdue book(s), please return ASAP.'
            }
        elif current_borrow + current_reserve >= book_limit:
            context = {
                'msg': 'Failed! Max borrow quota reached.'
            }
        elif BookInstance.objects.filter(q1 & q2).count() > 0:
            x = BookInstance.objects.filter(q1 & q2).values_list()[:1].get()[0]
            FK = BookInstance.objects.get(BookInstanceID=x)
            BookInstance.objects.filter(BookInstanceID=x).update(Status='On Loan')
            BorrowRecord.objects.create(
                BookInstanceID=FK,
                UserID=request.user,
                BorrowDate=now,
                DueDate=now + delta,
            )
            context = {
                'msg': 'Success! You have borrowed ' + x + '.'
            }
        elif Reserve.objects.filter(q1 & q3 & q5).count() > 0:
            context = {
                'msg': 'Failed! You already reserved this book.'
            }
        else:
            FK = Book.objects.get(BookID=book_selected)
            Reserve.objects.create(
                BookID=FK,
                UserID=request.user,
                ReserveDate=now,
            )
            context = {
                'msg': 'Success! You are now in waiting list.'
            }
        return render(request, 'lms/notification.html', context)


def book_mgt(request):
    if request.method == 'POST':
        search_text = request.POST['search']
        q1 = Q(BookID__icontains=search_text)
        q2 = Q(Publisher__icontains=search_text)
        q3 = Q(Title__icontains=search_text)
        q4 = Q(Author__icontains=search_text)
        book_list = Book.objects.filter(q1 | q2 | q3 | q4)
    else:
        book_list = Book.objects.all()
    return render(request, 'lms/book_mgt.html', {'book_list': book_list})



class BookMgtListView(ListView):

    template_name = 'lms/book_mgt.html'
    paginate_by = 5

    def get_queryset(self):
        if self.request.GET.get('search'):
            search_text = self.request.GET.get('search')
            q1 = Q(BookID__icontains=search_text)
            q2 = Q(Author__icontains=search_text)
            q3 = Q(Title__icontains=search_text)
            q4 = Q(Publisher__icontains=search_text)
            book_list = Book.objects.filter(q1 | q2 | q3 | q4)
            return book_list
        else:
            book_list = Book.objects.all()
            return book_list

    def get_context_data(self, **kwargs):
        context = super(BookMgtListView, self).get_context_data(**kwargs)
        books = self.get_queryset()
        page = self.request.GET.get('page')
        paginator = Paginator(books, self.paginate_by)
        try:
            books = paginator.page(page)
        except PageNotAnInteger:
            books = paginator.page(1)
        except EmptyPage:
            books = paginator.page(paginator.num_pages)

        context['book_list'] = books
        return context


def book_edit(request):
    if request.method == 'POST':
        book_selected = request.POST['BookID']
        q1 = Q(BookID__iexact=book_selected)
        item = Book.objects.get(q1)
        if request.POST['action'] == "view":
            form = BookModelForm(instance=item)
            context = {
                'form': form, 'BookID': book_selected}
            return render(request, 'lms/book_edit.html', context)
        elif request.POST['action'] == "submit":
            if Book.objects.filter(ISBN__iexact=request.POST['ISBN']).exclude(BookID = request.POST['BookID']).count() > 0:
                messages.error(request, 'Error! The ISBN is already exists.', extra_tags='ISBN')
                form = BookModelForm(request.POST)
                context = {
                    'form': form, 'BookID': request.POST['BookID']}
                return render(request, 'lms/book_edit.html', context)
            else:
                form = BookModelForm(request.POST, instance=item)
                if form.is_valid():
                    form.save()
                    book_list = Book.objects.all()
                    return render(request, 'lms/book_mgt.html', {'book_list': book_list})


def book_new(request):
    if request.method == 'POST':
        if request.POST['action'] == "view":
            form = BookModelForm()
            context = {
                'form': form}
            return render(request, 'lms/book_new.html', context)
        elif request.POST['action'] == "submit":
            form = BookModelForm(request.POST)
            error = False
            context = {
                'form': form}
            if Book.objects.filter(BookID__iexact=request.POST['BookID']).count() > 0:
                messages.error(request, 'Error! The BookID is already exists.', extra_tags='BookID')
                error = True
            if Book.objects.filter(ISBN__iexact=request.POST['ISBN']).count() > 0:
                messages.error(request, 'Error! The ISBN is already exists.', extra_tags='ISBN')
                error = True
            if error:
                return render(request, 'lms/book_new.html', context)
            else:
                form = BookModelForm(request.POST)
                number = request.POST['number']
                if form.is_valid():
                    f = form.save(commit=False)
                    f.BookID = form.cleaned_data.get("BookID")
                    book_selected = f.BookID
                    f.save()
                    FK = Book.objects.get(BookID=book_selected)
                    for i in range(int(number)):
                        x = str(i + 1).zfill(2)
                        BookInstance.objects.create(
                            BookID=FK,
                            Status='Maintenance',
                            BookInstanceID=book_selected + "." + x
                        )
                    book_list = Book.objects.all()
                    return render(request, 'lms/book_mgt.html', {'book_list': book_list})
                else:
                    msg = form.errors
                    messages.error(request, msg, extra_tags='Others')
                    return render(request, 'lms/book_new.html', context)


def bookinstance_mgt(request):
    if request.method == 'POST':
        book_selected = request.POST['BookID']

lms/templates/lms/_pagination.html
{% with request.get_full_path as querystring %}
{% if "/?" in querystring %}
<nav aria-label="navigation">
    <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="{{querystring}}&page={{ page_obj.previous_page_number }}">
            <span class="sr-only">Previous</span>
        <</a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <span class="sr-only">Previous</span>
        <</a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="{{querystring}}&page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="{{querystring}}&page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="{{querystring}}&page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="{{querystring}}&page={{ page_obj.next_page_number }}">>
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">>
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>
</nav>
{% else %}

<nav aria-label="navigation">
    <ul class="pagination justify-content-end mb-0">
{% if page_obj.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span class="sr-only">Previous</span>
        <</a>
    </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">
            <span class="sr-only">Previous</span>
        <</a>
    </li>
{% endif %}

{% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active">
        <a class="page-link" href="?page={{ i }}">{{ page_obj.number }}</a>
      </li>
    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
    <li class="page-item">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endif %}
{% endfor %}

{% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
    <li><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
{% endif %}

{% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">>
          <span class="sr-only">Next</span>
        </a>
      </li>
{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">>
            <span class="sr-only">Next</span>
        </a>
    </li>
{% endif %}
</ul>
</nav>

{% endif %}
{% endwith %}

lms/templates/lms/base.html
<!DOCTYPE html>
<html lang="en">
<head>

	<title>LMS</title>

{% load static %}

     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="team" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <link rel="stylesheet" href="{% static 'lms/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'lms/css/owl.carousel.css' %}">
     <link rel="stylesheet" href="{% static 'lms/css/owl.theme.default.min.css' %}">
     <link rel="stylesheet" href="{% static 'lms/css/font-awesome.min.css' %}">

     <!-- MAIN CSS -->
     <link rel="stylesheet" href="{% static 'lms/css/tooplate-style.css' %}">

</head>
<body>

     <!-- PRE LOADER -->
     <section class="preloader">
          <div class="spinner">

               <span class="spinner-rotate"></span>

          </div>
     </section>


     <!-- MENU -->
     <section class="navbar custom-navbar navbar-fixed-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    {% if user.is_authenticated %}
                    <a href="{% url 'index' %}" class="navbar-brand">{{ user.username }}'s LMS</a>
                    {% else %}
                    <a href="{% url 'index' %}" class="navbar-brand">LMS</a>
                    {% endif %}
               </div>

               <!-- MENU LINKS -->

               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                         {% if user.is_authenticated %}
                         <li><a href="{% url 'index' %}" class="smoothScroll">Search</a></li>
                         {% endif %}
                         {% if user.is_staff %}
                         <li><a href="{% url 'book_mgt' %}" class="smoothScroll">Book</a></li>
                         <li><a href="{% url 'check_in' %}" class="smoothScroll">Check-in</a></li>
                         <li><a href="{% url 'maintenance' %}" class="smoothScroll">Maintenance</a></li>
                         <li><a href="/lms/picking_list/today/" class="smoothScroll">Picking List</a></li>
                         {% endif %}
                         {% if user.is_authenticated %}
                         <li><a href="{% url 'record' %}" class="smoothScroll">My Record</a></li>
                         <li><a href="{% url 'logout' %}" class="smoothScroll">Logout</a></li>
                         {% else %}
                         <li><a href="{% url 'login' %}">Login</a></li>
                         {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                         <li></li>
                    </ul>
               </div>
          </div>
     </section>

     <!-- CONTENT -->

     <section id="home" data-stellar-background-ratio="0.5">
          <div class="overlay"></div>
     {% if user.is_authenticated %}

     {% block content %}{% endblock %}

     {% endif %}

     </section>

     <!-- SCRIPTS -->
     <script src="{% static 'lms/js/jquery.js' %}"></script>
     <script src="{% static 'lms/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'lms/js/jquery.stellar.min.js' %}"></script>
     <script src="{% static 'lms/js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'lms/js/smoothscroll.js' %}"></script>
     <script src="{% static 'lms/js/custom.js' %}"></script>

</body>
</html>

lms/templates/lms/bookinstance_edit.html
{% extends 'lms/base.html' %}

{% block content %}

          <div class="container">
               <div class="row">
                    <div class="col-md-offset-3 col-md-6 col-sm-12">
                        <div class="home-info">
                            <form action="" method="POST" > {% csrf_token %}
                                <a style="color:white;text-align: left;font-size:28px;">Edit book:</a> <br>
                                <div style="display:flex; flex-direction: row">
                                    <label class="form-group col-md-4" style="text-align: left; color: white;">{{ form.BookInstanceID.label}}</label>
                                    <label class="form-group col-md-8" style="text-align: left; color: white;">{{ BookInstanceID }}</label>
                                </div>
                                <div style="display:none;">
                                    {{form.BookID}}
                                    {{form.BookInstanceID}}
                                </div>
                                <div style="display:flex; flex-direction: row">
                                    <label class="form-group col-md-4" style="text-align: left; color: white;">{{ form.Status.label}}</label>
                                    {{form.Status}}
                                </div>
                                    {% for message in messages %}
                                        {%if "Others" in message.tags %}
                                                <a class="form-group col-md-8" style="text-align: left; color: yellow;">{{ message }}</a><br><br>
                                        {% endif %}
                                    {% endfor %}
                                <input type="text" name="action" id="action" style="display:none;" value ="submit" >
                                <input type="text" name="BookInstanceID" id="BookInstanceID" style="display:none;" value = {{ BookInstanceID }} >
                                <button type="submit" class="form-control" id="submit"> Submit </button>
                            </form>
                        </div>
                    </div>
               </div>
          </div>

{% endblock %}

lms/templates/lms/record.html
{% extends 'lms/base.html' %}

{% block content %}

          <div class="container">
               <div class="row">
                    <div class="col-md-offset-3 col-md-6 col-sm-12">
                        <div class="home-info">
                            <a style="color:white;text-align: left;font-size:20px;">UserID: {{user.id}}</a> <br>
                            <a style="color:white;text-align: left;font-size:20px;">Username: {{user.username}}</a> <br>
                            <a style="color:white;text-align: left;font-size:20px;">Unreturned books: {{ unreturn_count }}</a> <br>
                            <a style="color:white;text-align: left;font-size:20px;">Reserved books: {{ reserve_count}}</a> <br>
                            <a style="color:white;text-align: left;font-size:20px;">Remaining quota: {{ remain_count }}</a> <br>
                            <br>
                            <a style="color:white;text-align: left;font-size:36px;">Current reserved books:</a> <br>
                            <table class="table">
                                <thead>
                                    <tr style="text-align: left; color: white;">
                                        <th>Reserve ID</th>
                                        <th>Book ID</th>
                                        <th>Reserve Date</th>
                                        <th>Position</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for reserve in reserve_list %}
                                    <tr style="text-align: left; color: white;">
                                        <td>{{ reserve.ReserveID }}</td>
                                        <td>{{ reserve.BookID_id }}</td>
                                        <td>{{ reserve.ReserveDate }}</td>
                                        <td>{{ reserve.Waiting }}</td>
                                        <td>
                                            <form action="/lms/reserve_cancel/" method="POST" > {% csrf_token %}
                                                <input type="text" name="ReserveID" id="ReserveID" style="display:none;" value = {{ reserve.ReserveID }} >
                                                <button type="submit" class="form-control" id="submit"> Cancel </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="home-info">
                            <a style="color:white;text-align: left;font-size:36px;">Borrow Record:</a> <br>
                            <table class="table">
                                <thead>
                                    <tr style="text-align: left; color: white;">
                                        <th>Borrow ID</th>
                                        <th>Book Instance ID</th>
                                        <th>Borrow Date</th>
                                        <th>Due Date</th>
                                        <th>Return Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for borrow in borrow_list %}
                                    {% if borrow.IsOverdue %}
                                    <tr style="text-align: left; color: yellow;">
                                    {% else %}
                                    <tr style="text-align: left; color: white;">
                                    {% endif %}
                                        <td>{{ borrow.BorrowID }}</td>
                                        <td>{{ borrow.BookInstanceID_id }}</td>
                                        <td>{{ borrow.BorrowDate }}</td>
                                        <td>{{ borrow.DueDate }}</td>
                                        <td>{{ borrow.ReturnDate }}</td>
                                        <td>
                                            {% if borrow.ReturnDate == None %}
                                            <form action="/lms/extend/" method="POST" > {% csrf_token %}
                                                <input type="text" name="BorrowID" id="BorrowID" style="display:none;" value = {{ borrow.BorrowID }} >
                                                <button type="submit" class="form-control" id="submit"> Extend </button>
                                            </form>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% if is_paginated %}
                            {% include "lms/_pagination.html" %}
                        {% endif %}
                    </div>
               </div>
          </div>

{% endblock %}